AWS_ACCESS_KEY: "AKIAIGFVJTBBXEQQCZCQ"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "dropque-staging"



SENDGRID_USERNAME: app59659234@heroku.com
SENDGRID_PASSWORD: 2pschp8o7050
